#!/usr/bin/env python3

"""build.py

Usage:
  build.py [--out=<dir>] [--root=<url>]
  build.py (-h | --help)

Options:
  -h --help       Show this screen.
  --out=<dir>     Directory to generate site in [default: _site]
  --root=<url>    Root of the website [default: https://memo.barrucadu.co.uk/]

"""

import os
import pypandoc
import subprocess
import yaml

from bs4 import BeautifulSoup
from datetime import datetime, timedelta
from distutils.dir_util import create_tree, copy_tree
from docopt import docopt
from jinja2 import Environment, FileSystemLoader, select_autoescape


class MemoReader:
    def __init__(self, memodir="memos"):
        self.memodir = memodir

    def memos(self):
        """Read and parse all memos.
        """

        memos = []
        tag_names = []

        for memofile in os.listdir(self.memodir):
            fpath = os.path.join(self.memodir, memofile)
            if not os.path.isfile(fpath):
                continue

            with open(fpath, "r") as f:
                frontmatter, content, memo_tag_names = MemoReader.__split_frontmatter_content(fpath, f.readlines())

            memo = frontmatter
            rendered, toc = MemoReader.__pandocise_memo_content(memofile, content)
            memo["content"] = rendered
            if toc != []:
                memo["toc"] = toc
            memo["raw_content"] = content

            memos.append(memo)
            tag_names.extend(memo_tag_names)

        return memos, MemoReader.__make_tags(set(tag_names))


    @staticmethod
    def __split_frontmatter_content(fpath, lines):
        """Split a file into frontmatter and content, and interpret the
        frontmatter as a YAML document.
        """

        # structure of a document is:
        #
        #    ---
        #    yaml frontmatter
        #    ---
        #    content
        #
        # there may be more '---'s in the content, so we want the
        # index of the first one after the initial line.
        idx = lines[1:].index("---\n") + 1

        frontmatter = yaml.load("".join(lines[1:idx]), Loader=yaml.SafeLoader)
        content = "".join(lines[idx + 1:])

        # add the implicit frontmatter
        if "slug" not in frontmatter:
            frontmatter["slug"], _ = os.path.splitext(os.path.basename(fpath))
        if "published" not in frontmatter:
            datestr = subprocess.check_output(["git", "log", "--diff-filter=A", "--follow", "--date=short", "--format=%ad", "-1", "--", fpath])
            try:
                frontmatter["published"] = datetime.strptime(datestr.decode("utf-8").strip(), "%Y-%m-%d")
            except:
                # this will be reached if the file hasn't been committed
                frontmatter["published"] = datetime.now()
        frontmatter["published_iso"] = frontmatter.get("published_iso", frontmatter["published"].strftime("%Y-%m-%d"))
        frontmatter["published_pp"] = frontmatter.get("published_pp", frontmatter["published"].strftime("%B %-d, %Y"))
        frontmatter["modified"] = frontmatter.get("modified", frontmatter.get("date", frontmatter["published"]))
        frontmatter["modified_iso"] = frontmatter.get("modified_iso", frontmatter["modified"].strftime("%Y-%m-%d"))
        frontmatter["modified_pp"] = frontmatter.get("modified_pp", frontmatter["modified"].strftime("%B %-d, %Y"))
        if not isinstance(frontmatter["published"], datetime):
            frontmatter["published"] = datetime(frontmatter["published"].year, frontmatter["published"].month, frontmatter["published"].day)
        if not isinstance(frontmatter["modified"], datetime):
            frontmatter["modified"] = datetime(frontmatter["modified"].year, frontmatter["modified"].month, frontmatter["modified"].day)

        # mangle the 'tags' field into a list
        tag_names = frontmatter.get("tags", [])
        if type(tag_names) is str:
            tag_names = [name.strip() for name in tag_names.split(",")]
        frontmatter["tags"] = MemoReader.__make_tags(tag_names)

        return frontmatter, content, tag_names


    @staticmethod
    def __pandocise_memo_content(memofile, content):
        """Render a memo's content using pandoc.
        """

        _, fmt = os.path.splitext(memofile)
        fmt = fmt[1:]
        if fmt == "lhs":
            fmt = "markdown+literate_haskell"

        rendered = pypandoc.convert_text(content, "html", format=fmt,
            filters=[
                "pandoc-sidenote",
                "pandoc-filter-transform-code",
            ],
            extra_args=[
                "--no-highlight",
            ],
        )

        toc = []
        for h2 in BeautifulSoup(rendered, features="html.parser").find_all("h2"):
            toc.append({
                "title": h2.text,
                "anchor": h2["id"],
            })

        return rendered, toc

    @staticmethod
    def __make_tags(tag_names):
        """Turn a list of tag names into tag objects.
        """

        return [
            { "name": name, "slug": name.lower().replace(" ", "-") }
            for name in tag_names
        ]


class WebsiteBuilder:
    def __init__(self, outdir, siteroot, tpldir="templates"):
        self.outdir = outdir
        self.siteroot = siteroot
        self.tagdir = "tag/"

        self.env = Environment(
            loader=FileSystemLoader(tpldir),
            autoescape=False,
        )


    def copy(self, source, subdir=False):
        """Copy the 'source' into the $target directory.

        If 'subdir' is true, copy 'source' to $target/'source'.
        """

        target = self.outdir
        if subdir:
            target = os.path.join(self.outdir, source)

        copy_tree(source, target)


    def robots(self):
        """Render the robots.txt.
        """

        self.__render("robots.txt", "robots.txt")


    def sitemap(self, memos, tags):
        """Render an XML sitemap.
        """

        self.__render("sitemap.xml", "sitemap.xml",
            memos=memos,
            tags=tags,
        )


    def memo_list(self, memos, tag=None):
        """Render a memo listing page.
        """

        fname = "index.html"
        if tag is not None:
            fname = os.path.join(self.tagdir, tag["slug"] + ".html")
            memos = [memo for memo in memos if tag in memo["tags"]]

        self.__render(fname, "list.html",
            title=WebsiteBuilder.__title_for(tag),
            tag=tag,
            memos=memos,
        )


    def memo_feed(self, memos, tag=None, num=10):
        """Render a memo listing feed.
        """

        fname = "atom.xml"
        if tag is not None:
            fname = os.path.join(self.tagdir, tag["slug"] + ".xml")
            memos = [memo for memo in memos if tag in memo["tags"]]

        metadata = {
            "title": WebsiteBuilder.__title_for(tag),
            "tag": tag,
            "memos": memos[:num],
        }
        if memos:
            metadata["feed_date"] = memos[0]["modified_iso"]

        self.__render(fname, "atom.xml", **metadata)


    def memo(self, memo):
        """Render a memo.
        """

        self.__render(memo["slug"] + ".html", "memo.html", **memo)


    def __render(self, fname, tplfile, tag=None, **kwargs):
        """Render a template to a file.  The file name is interpreted relative
        to the base directory.
        """

        create_tree(self.outdir, [fname])

        tplargs = {
            "is_root": fname == "index.html",
            "site_name": WebsiteBuilder.__title_for(None),
            "site_root": self.siteroot,
            "tag_dir": self.tagdir,
            "url": fname,
        }

        if tag is not None:
            tplargs["tag"] = tag

        template = self.env.get_template(tplfile)
        rendered = template.render(**tplargs, **kwargs)

        with open(os.path.join(self.outdir, fname), "w") as f:
            print(rendered, file=f)


    @staticmethod
    def __title_for(tag=None):
        """Title for a memo listing or feed.
        """

        if tag is None:
            return "barrucadu's memos"

        return f"barrucadu's memos - tagged '{tag['name']}'"


args = docopt(__doc__)

memos, tags = MemoReader("memos").memos()

memos_for_lists = sorted(
    [memo for memo in memos if "deprecated_by" not in memo],
    key=lambda memo: memo["modified"] + timedelta(days=(365*1000 if "important" in memo else 0)),
    reverse=True
)

memos_for_feeds = sorted(
    [memo for memo in memos_for_lists if memo["audience"].lower() != "personal"],
    key=lambda memo: memo["modified"],
    reverse=True
)

builder = WebsiteBuilder(args["--out"], args["--root"])

builder.copy("static")
builder.copy("css") # todo - minify
builder.copy("MathJax", subdir=True)

builder.robots()
builder.sitemap(memos, tags)

builder.memo_list(memos_for_lists)
builder.memo_feed(memos_for_feeds)

for tag in tags:
    builder.memo_list(memos_for_lists, tag=tag)
    builder.memo_feed(memos_for_feeds, tag=tag)

for memo in memos:
    builder.memo(memo)
