on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: nix
    steps:
      - name: Install tools
        run: |
          nix-env -iA nixpkgs.nodejs_24 nixpkgs.rsync
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          nix --extra-experimental-features "nix-command flakes" develop --command bash -c ./build
      - name: Deploy carcosa
        run: bash -e .forgejo/scripts/deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CARCOSA_SSH_PRIVATE_KEY }}
          TARGET: carcosa.barrucadu.co.uk
      - name: Deploy yuggoth
        run: bash -e .forgejo/scripts/deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.YUGGOTH_SSH_PRIVATE_KEY }}
          TARGET: yuggoth.barrucadu.co.uk
