resource_types:
  - name: rsync-resource
    type: docker-image
    source:
      repository: registry.barrucadu.dev/rsync-resource
      username: registry
      password: ((docker-registry-password))

resources:
  - name: builder-git
    type: git
    source:
      uri: https://github.com/barrucadu/memo.barrucadu.co.uk.git
      paths:
        - concourse/Dockerfile
  - name: builder-image
    type: docker-image
    source:
      repository: registry.barrucadu.dev/memo-builder
      username: registry
      password: ((docker-registry-password))
  - name: memo-git
    type: git
    source:
      uri: https://github.com/barrucadu/memo.barrucadu.co.uk.git
  - name: memo-rsync
    type: rsync-resource
    source:
      server: dunwich.barrucadu.co.uk
      remote_dir: /srv/http/barrucadu.co.uk/memo
      private_key: ((dunwich-ssh-private-key))

jobs:
  - name: update-pipeline
    plan:
      - get: memo-git
        trigger: true
      - set_pipeline: memo-barrucadu-co-uk
        file: memo-git/concourse/pipeline.yml

  - name: memo-builder
    serial: true
    plan:
      - get: builder-git
        trigger: true
      - put: builder-image
        params:
          build: builder-git
          dockerfile: builder-git/concourse/Dockerfile
          tag_as_latest: true

  - name: build-and-deploy
    serial: true
    plan:
      - get: builder-image
      - get: memo-git
        trigger: true
      - task: build-site
        image: builder-image
        params:
          OUT_DIR: memo
        config:
          platform: linux
          inputs:
            - name: memo-git
          outputs:
            - name: site
          run:
            dir: memo-git
            path: sh
            args:
              - -cex
              - |
                virtualenv venv
                source venv/bin/activate
                pip install -r requirements-freeze.txt
                PATH=.:$PATH ./build --out="../site/${OUT_DIR}"
      - put: memo-rsync
        params:
          path: site/memo
          rsync_args:
            - --delete
      - task: notify
        params:
          PLEROMA_PASSWORD: ((pleroma-user-memo-password))
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.8
          inputs:
            - name: memo-git
          run:
            dir: memo-git
            path: sh
            args:
              - -cex
              - |
                pip install -r requirements.txt
                ./post-pleroma-status
