resource_types:
  - name: rsync-resource
    type: docker-image
    source:
      repository: registry.barrucadu.dev/rsync-resource
      username: registry
      password: ((docker-registry-password))

resources:
  - name: memo-git
    type: git
    source:
      uri: https://github.com/barrucadu/memo.barrucadu.co.uk.git
  - name: memo-rsync--carcosa
    type: rsync-resource
    source:
      server: carcosa.barrucadu.co.uk
      remote_dir: /persist/srv/http/barrucadu.co.uk/memo
      private_key: ((carcosa-ssh-private-key))
  - name: memo-rsync--yuggoth
    type: rsync-resource
    source:
      server: yuggoth.barrucadu.co.uk
      remote_dir: /persist/srv/http/barrucadu.co.uk/memo
      private_key: ((carcosa-ssh-private-key))

jobs:
  - name: update-pipeline
    plan:
      - get: memo-git
        trigger: true
      - set_pipeline: memo-barrucadu-co-uk
        file: memo-git/concourse/pipeline.yml

  - name: build-and-deploy
    serial: true
    plan:
      - get: memo-git
        trigger: true
      - task: build-site
        params:
          OUT_DIR: memo
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: nixos/nix
          inputs:
            - name: memo-git
          outputs:
            - name: site
          run:
            dir: memo-git
            path: sh
            args:
              - -cex
              - |
                nix --extra-experimental-features "nix-command flakes" develop --command bash -c "./build --out=../site/${OUT_DIR}"
      - put: memo-rsync--carcosa
        no_get: true
        params:
          path: site/memo
          rsync_args:
            - --delete
      - put: memo-rsync--yuggoth
        no_get: true
        params:
          path: site/memo
          rsync_args:
            - --delete
